# Generated by Django 5.1.1 on 2024-10-02 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registryitem',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registryitem',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='registryitem',
            name='password',
        ),
        migrations.AddField(
            model_name='guest',
            name='firstName',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='lastName',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='password',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='picture',
            field=models.ImageField(upload_to='guest_pictures/'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='homepage.guest')),
            ],
        ),
    ]
