# Generated by Django 5.1.1 on 2024-10-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_firstname_registryitem_name_remove_guest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='registryItem',
        ),
    ]
