# Generated by Django 5.1.1 on 2024-10-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_guest_guestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryitem',
            name='url',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
