# Generated by Django 5.1.1 on 2024-10-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_registryitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='guest',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
